#!/usr/local/captive-env/bin/python

""" remove one client entry from  CAPTIVE_PASSLIST from its IP """

import sys

from portal_filter import remove_from_passlist

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} IP_ADDR")
    sys.exit(1)

if remove_from_passlist(ip_addr=sys.argv[1].strip()):
    print("removed")
else:
    print("not present")
