#!/usr/local/captive-env/bin/python

""" Periodic maint tasks

    PERIODIC: every `INTERVAL`, clear the passlist
        by removing inactive users from the passlist, we are preventing
        new users on same device to be automatically registered and bypassed
        so they will see the portal.
        An additional system is already in place in the portal with `TIMEOUT`,
        forcing users to re-register after some time. """

import logging
import os
import time
from threading import Thread

from portal_filter import clear_passlist


INTERVAL: int = int(os.getenv("CLEAR_PASSLIST_INTERVAL", 60)) * 60  # seconds
logging.basicConfig(level=logging.DEBUG if os.getenv("DEBUG") else logging.INFO)
logger = logging.getLogger("watcher")


class PeriodicPasslistClearance(Thread):
    def run(self, *args, **kwargs):
        elapsed: int = 0
        while True:
            time.sleep(1)
            elapsed += 1
            if elapsed >= INTERVAL:
                logger.debug("CLEAR_PASSLIST_INTERVAL reached")
                clear_passlist(inactives_only=True)
                elapsed = 0


def main():
    periodic = PeriodicPasslistClearance()
    periodic.start()

    logger.info("watcher done")


if __name__ == "__main__":
    main()
